[site]
title = "Libin Zhu"
description = "Personal website of Libin Zhu"
favicon = "/icon.svg"
last_updated = "Dec 15, 2025"

[author]
name = "Libin Zhu"
title = "Postdoc"
institution = "University of Washington"
avatar = "/bio.JPG"

[social]
# Contact information (leave blank or delete to hide)

email = "libinzhu@uw.edu"
location = "Seattle, WA"
google_scholar = "https://scholar.google.com/citations?user=hyTGiUcAAAAJ&hl=en&oi=ao"
github = "https://github.com/zhm1995"
linkedin = "https://www.linkedin.com/in/libin-zhu-3a34291b5"

[features]
# Show a like button on the about page


# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "link"
href = "/cv.pdf"

[[navigation]]
title = "Miscellaneous"
type = "page"
target = "miscellaneous"
href = "/miscellaneous"